### ISSUE TITLE
NO VALUE AVAILABLE FOR host 

### ISSUE THREAD

**Issue by pratibhakalmath** [SAP/jenkins-pipelines#15] opened 2019-03-14 05:54 UTC
Hi there , I am getting an issue saying " NO VALUE AVAILABLE FOR host " in stage("Deploy Fiori App"). Please suggest on the same.

**Comment by pratibhakalmath** [comment] 2019-03-14 10:45
[Error Details.txt](https://github.com/SAP/jenkins-pipelines/files/2965936/Error.Details.txt)

**Comment by daniel-kurzynski** [comment] 2019-03-14 11:51
The interface of neoDeploy has changed and the compatibility layer was removed in the latest version.
Host and account were moved into a neo configuration map:
```
neoDeploy script: this, source: 'path/to/archiveFile.mtar', neo: [credentialsId: 'my-credentials-id', host: 'hana.example.org', account: 'myAccount']
```
Example from here:
https://github.com/SAP/jenkins-library/blob/master/documentation/docs/steps/neoDeploy.md#example

The same applies for the configuration in the yml file.

**Comment by pratibhakalmath** [comment] 2019-03-15 05:53
Hi Daniel, I tried your suggestion but Ia m getting a new error now.Please help undeststand the same.
Thanks.
[Error Details(1).txt](https://github.com/SAP/jenkins-pipelines/files/2969614/Error.Details.1.txt)

**Comment by marcusholl** [comment] 2019-03-15 07:02
From what I understand reading the log neo.sh is not in the path on the Jenkins server. I would like to suggest to put neo.sh into the path. Either by adding it to the path directly or by putting a symbolic link into `/usr/local/bin`, which is maybe the more easy way.

**Comment by pratibhakalmath** [comment] 2019-03-19 12:49
Hi Marcusholl, we added the neo.sh into the path but getting a different error. Please help undeststand the same.
Thanks.
[Error Details(2).txt](https://github.com/SAP/jenkins-pipelines/files/2983345/Error.Details.2.txt)

**Comment by marcusholl** [comment] 2019-03-19 13:03
Thank you for the response. The neo toolset is not in the path:

```
+ neo.sh deploy-mta --synchronous --host hanatrial.ondemand.com --account p1942404349trial --user **** --password **** --source MyMTAApp.mtar
/home/jenkins/jenkins_slave/workspace/Piper_GitHub_Test/src@tmp/durable-a6a5ad99/script.sh: line 1: neo.sh: command not found
```

Maybe it is only in the path on Jenkins master, but we are on a slave, apparently. In this case I would like to suggest to put the neo toolset also into the path on the slave. In case my assumtion is wrong, please check for more details under Jenkins > Manage Jenkins > System Information. Here we can find the path. The `$NEO_HOME/bin` directory should be denoted here or there must be a link from e.g. /usr/local/bin to $NEO_HOME/bin.

There was also a trace for being on a slave node in your previous log file. Sorry for not pointing out to that already earlier.

**Comment by pratibhakalmath** [comment] 2019-03-20 11:57
Hi Marcusholl, we are getting an error like below. Please help us resolve the same. Thanks.

Error occurred during initialization of VM
java.lang.Error: java.lang.ClassNotFoundException: com.sap.jpaas.infrastructure.console.CmdJarsClassLoader
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1469)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)
Caused by: java.lang.ClassNotFoundException: com.sap.jpaas.infrastructure.console.CmdJarsClassLoader
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2209)
	at java.lang.SystemClassLoaderAction.run(ClassLoader.java:2195)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.lang.ClassLoader.initSystemClassLoader(ClassLoader.java:1456)
	at java.lang.ClassLoader.getSystemClassLoader(ClassLoader.java:1436)

**Comment by marcusholl** [comment] 2019-03-21 09:33
I investigated the issue using neo version `2.153.8.1`. Versions mentioned below depends on that version and might slightly vary.

We have a problem with the class path setup.

The class mentioned above in the trace is `com/sap/jpaas/infrastructure/console/CmdJarsClassLoader`.

This class comes from jar file: `com.sap.jpaas.infrastructure.console.classloader-2.32.0.jar`

The classpath setup is done by `$NEO_HOME/bin/neo.sh`. Inside this script the classpath in named `toolcp`. `$NEO_HOME` is not an explict environment variable, it just denotes the folder which was used for installing the neo toolset.

This classpath (`toolcp`) is setup based on a variable `basePath`. That `basePath` in turn is setup by something like `ls -l "${script}" | sed 's/^.*-> //'`. `$script` in turn is $0, this means the initial tool call.

The problem is now either
1.) `$0` is wrong in your case
2.) the script above expects symbolic links to be displayed like `neo.sh -> /opt/sap/neo/bin/neo.sh ` The important part is the `->`. Maybe this does  fit  on your operating system.

In order to resolve the issue I would like to propose to call a `ls -l` for the folder containing `which neo.sh` and check if the format of `ls -l` fits into the assumptions in your case.

Additionally it would be helpful to add some log lines into neo.sh in order to drill down the issue. E.g. `echo "[INFO] First argument: $0"` right at the beginning of the script.  And another line after the line containing `ls -l "${script}" | sed 's/^.*-> //'`:  `echo "[INFO] SCRIPT: $script"`.

And a last log message before executing java at the bottom of the script:

`echo "[INFO] Tool classpath $toolcp"`

**Comment by pratibhakalmath** [comment] 2019-03-22 05:27
Hi Marcusholl , thanks for the response. Can you please verify my Jenkinsfile, just to be sure all is fine.Thanks.
[Jenkinsfile.txt](https://github.com/SAP/jenkins-pipelines/files/2995097/Jenkinsfile.txt)

**Comment by marcusholl** [comment] 2019-03-22 08:13
Dear customer,

I'm out of office today on a workshop. I had a look on your Jenkinsfile and I think the reason for our issue here is not in the Jenkinsfile.

The reason is: we are not able to setup the classpath. I will provide a more detailed response later this day.

**Comment by marcusholl** [comment] 2019-03-22 10:22
The issue is IMO caused by a failure when resolving the classpath.

Please go into your neo.sh file and put this line

```
echo "[INFO] Classpath: $toolcp"
```

right before 

```
exec "$javaExe" ... 
```

which is right at the end of that script file.

I believe we will not see a log output containing something like

```
com.sap.jpaas.infrastructure.console.classloader-2.32.0.jar
```

As a next step we have to find out why class path resolution does not work on your side.

In order to fight down this, please add this line

```
echo "[INFO] SCRIPT: $script" 
```

right after

```
script=$(ls -l "${script}" | sed 's/^.*-> //') 
```

In order to trigger the script please use

```
neo.sh version
```

Please issue this command on the node to which the statement gets dispatched from your Jenkins.

Please update this thread with the log output created by the statements mentioned above.

Would also be interesting to issue `ls -l  $(which neo.sh)` in order to check how the format of the ls output looks like on your side. When having a symbolic link we should get `->` in the output. The script parses for that `->`.  Maybe the format is somehow different on your side (.... unlikely, but you now, we never know ...).

I am using version `2.153.8.1`. Depending on the version available on your side the script file might look different. In this case please try to find the similar places in the script file or just tell me your version so that I can provide an update matching your version.

**Comment by marcusholl** [comment] 2019-03-25 08:09
Are there any updates which can be shared?

**Comment by pratibhakalmath** [comment] 2019-03-25 09:37
Hi Marcusholl , thanks for the response. PFA of the outputs for the commands run on neo.sh as per your suggestion.Thanks.
[neo.sh.docx](https://github.com/SAP/jenkins-pipelines/files/3002546/neo.sh.docx)

**Comment by marcusholl** [comment] 2019-03-25 10:48
In the word document I can see two different kinds of calls to `neo.sh`.

1.) `sudo sh neo.sh`
2.) `neo.sh version`

The first call outputs

`[INFO] Classpath: ./lib/cmd/com.sap.jpass.infrastructure.console.classloader-2.22.0.jar`

The second call returns with the already well known stack trace.

The `(!) ERROR: no arguments specified` observed for the first call means that neo.sh has been called without e.g. `version`.  I expect the first call to be successful when called like `sudo sh neo.sh version` (not fully sure if that needs to be quoted like: `sudo sh 'neo.sh version'`, or even: `sudo sh -c 'neo.sh version'`.  --> Please repeat the first call with an additional `version` and provide the result.

With regards to the second call (`neo.sh version`) we have to find why the classpath is not resolved properly. The line `echo "[INFO] SCRIPT: $script" ` does not produce any output in the log, hence we are not entering the corresponding loop. --> can you add more loggging, please:

`echo "[INFO] Initial version of SCRIPT: $script" ` right before the `while` loop.

Afterwards trigger the script again, with both ways:

1.) `sudo sh neo.sh version` (not sure about the quoting, see above, mind the version argument )
2.) `neo.sh version` 

and provide the output again.

**Comment by pratibhakalmath** [comment] 2019-03-26 05:49
Hi Marcusholl , we ran the commands as you suggested. Please find attached of the output for the same. Thanks.
[neo.sh command outputs.docx](https://github.com/SAP/jenkins-pipelines/files/3006684/neo.sh.command.outputs.docx)

**Comment by marcusholl** [comment] 2019-03-26 09:30
Hello,

now we know a little bit more ...

- `sudo sh neo.sh version` works fine. This returns the version as expected and:
- with `sudo sh neo.sh version` we can see the following log output
  - `[INFO] Initial version of SCRIPT: neo.sh`
  - `[INFO] Classpath: ./lib/cmd/com.sap.jpaas.infrastructure.console.classloader-2.22-0.jar`
- `neo.sh version` (without `sudo`) does not work, here we see the `ClassNotFoundException`
- with `neo.sh version` (without `sudo`) we do not see any log output

The classpath issue is triggered at the end of the script file when java gets invoked. Hence we should see the log output also when the `ClassNotFoundException` is raised. Our log output is expected to appear earlier before the stack trace. But there is nothing. Maybe we can add yet another log message right at the beginning of `neo.sh`. After the first line (`#!/bin/bash`) something like

```
echo "[INFO] invoking neo toolset"
```

I strongly expect this log message in _any_ case.

Can we be sure that in both cases the same `neo.sh` gets invoked? Maybe we have different versions of `neo.sh` in the path when being root and when being the standard user.

Can you issue `which` statements for both cases?
- `sudo which neo.sh`
- `which neo.sh`

Does the returned path point to the same file in both cases?

**Comment by pratibhakalmath** [comment] 2019-03-26 10:19
Hi Marcusholl , we ran the commands as you suggested. Please find attached of the output for the same. Thanks.
[neo.sh command outputs(1).docx](https://github.com/SAP/jenkins-pipelines/files/3007640/neo.sh.command.outputs.1.docx)

**Comment by marcusholl** [comment] 2019-03-26 11:50
OK, lets summarize again:

- `sudo neo.sh version` still works and shows all logs as expected.
- `neo.sh version` does not work, also showing no logs, but the `ClassNoFoundException`
- root does not have `neo.sh` in the path (path is `/usr/sbin`, `/usr/bin`, `/sbin` and `/bin`. The path does not contain `/usr/local/bin`, which is the location resolved by `which` for the standard user).
- the standard user has `neo.sh` in the path and it is resolved to `/usr/local/bin/neo.sh`.

I suppose for root neo.sh is used from the working dir (`/home/jenkins/NEO_HOME/tools`)

Again: I believe we have two different `neo.sh` scripts here. Reason for my assumption: in the case where is works we see not only the expected result (... the version is displayed), but we see also the log which we added. In the non working case we see the stack trace, but we can't see any log, which in fact is triggered before the trace happens.

`/usr/local/bin/neo.sh` should be a link. Can you figure out where it points to? E.g. `ls -la`. You should see an arrow `->` and after that arrow the location where the link points to. Beside the octets (`rwx`) there is also an `l`(like link) displayed. Please continue with resolving the link(s) until the final target. Other option: use `readlink` (`readlink -f /usr/local/bin/neo.sh`). Maybe `readlink` is not present on your distribution. Open the file and verify the log entries (`[INFO] ...`) added earlier. I guess there are no log entries and I guess we have a file different from `neo.sh` which gets called in conjunction with sudo.

**Comment by pratibhakalmath** [comment] 2019-03-27 06:26
Hi Marcusholl , thanks again for the response . I am not sure if I understood what all you suggested. But I have tried to run some test scripts . Please find attached of the results for the same.
[neo.sh command outputs(1).docx](https://github.com/SAP/jenkins-pipelines/files/3011806/neo.sh.command.outputs.1.docx)

**Comment by marcusholl** [comment] 2019-03-27 07:42
Hi,

`readlink -f /usr/local/bin/neo.sh` pointing to itself (`/usr/local/bin/neo.sh`) is the reason for our trouble. `neo.sh` work in the context of the installation, `neo.sh` expects the libs located in a folder `./lib` on the same level like the resolved `neo.sh` itself. `/usr/local/bin` does not contain the corresponding lib folder, of course. If it would contain it this would be an error.

Remove the `neo.sh` inside `/usr/local/bin` and create a symbolic link to the other `neo.sh` later. From our conversation I think I know some details about the folder layout on your side. So the command for that should be:

```
rm /usr/local/bin/neo.sh
ln -s /home/jenkins/NEO_NOME/tools/neo.sh /usr/local/bin/neo.sh
```

Afterwards `readlink -f /usr/local/bin/neo.sh` will point to `/home/jenkins/NEO_HOME/tools/neo.sh`

`neo.sh version` will work afterwards in both cases: when called as `root` and when called as standard user. Don't forget to remove the log we introduced while troubleshooting this issue.

Another story is: `root` does not have `/usr/local/bin` in the path as I saw earlier in our conversation. This is normally not required since `root` should not execute any script located in this folder. In case you would like to use `neo.sh` also with `root` (... I see no reason for that, but well ...) there are two options: 
- add `/usr/local/bin` to the path for `root`
- create the symbolic link mentioned above inside `/usr/bin`.

Both options comes with some disadvantages, basically I think there is no need to run Jenkins (and with that the neo toolset) as root.

**Comment by pratibhakalmath** [comment] 2019-03-27 09:40
Hi Marcusholl , thanks for the response . We implemented what you suggested and it seems the issue to be resolved as neo.sh version seems to be working fine. However, when we  run the Jenkins pipeline we are getting issue in "Clone sources and setup environment" stage itself .

    expected '<document start>', but found Scalar
        in 'reader', line 16, column 1:
    CI_DEPLOY_ACCOUNT='a533b9d89'

Attaching the detail error log as well as the config.properties file.Please help on the same.
[Error Details(2).txt](https://github.com/SAP/jenkins-pipelines/files/3012474/Error.Details.2.txt)
[config.properties.txt](https://github.com/SAP/jenkins-pipelines/files/3012471/config.properties.txt)

**Comment by marcusholl** [comment] 2019-03-27 12:56
We switched from properties to yaml quite some time ago and removed the properties support recently (commit `e282c07dd47917b85ebf6a190d17ac53a00f69cf`).

Anyway the project should switch to the yml configuration format. In order to get the support for properties back I would like to suggest to switch to an older commit: `0e7ef41fabce50fcb2c62a16e3bfb3e0c22bdcaa`. This commit can be configured under "Manage Jenkins" >>> "Configure System". Please let me know if this solves the issue.

Afterwards switch to the `yml` format, please. When this is done `master` (... or a recent tag) can be used again.

The yaml format looks like:

```
steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
    neo:
        credentialsId: 'CI_CREDENTIALS_ID'
        account: 'a533b9d89'
        host: 'eu1.hana.ondemand.com'
``` 

The yaml file is expected to be located in the project under `.pipeline/config.yml`

**Comment by pratibhakalmath** [comment] 2019-03-28 06:04
Hi Marcus , thanks for the update . We tried with the older commit like you suggested butwe got an error, details of which can be found in the attached. Please take a look on the issue and suggest us the resolution.Thanks.
[Error Details(2).txt](https://github.com/SAP/jenkins-pipelines/files/3016415/Error.Details.2.txt)

**Comment by marcusholl** [comment] 2019-03-28 07:46
```
log4j:ERROR setFile(null,true) call failed.
java.io.FileNotFoundException: /home/jenkins/NEO_HOME/tools/log/console_deploy-mta_1553752313264.log (Permission denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
```

Maybe there is no folder `/home/jenkins/NEO_HOME/tools/log/` or we have a permission issue.

Please check : `ls -la /home/jenkins/NEO_HOME/tools`
- In case there is no such folder create that folder: `mkdir -p /home/jenkins/NEO_HOME/tools/log`
- In case that folder does not belong to the user running Jenkins: change ther permissions accordingly: `chown -R jenkins:jenkins`. The `chown` command is only an example. Maybe you need to adjust the user/group according to your setup. A permission issue might be caused by installing the neo toolset as `root`.

**Comment by pratibhakalmath** [comment] 2019-03-28 11:58
Hi Marcus, we checked for the mentioned folder , the folder /home/jenkins/NEO_HOME/tools/log/ already exists and we assume has necessary permissions(PFA) , still we are getting the same issue , any leads on the same.
[neo.sh command outputs(1).docx](https://github.com/SAP/jenkins-pipelines/files/3017775/neo.sh.command.outputs.1.docx)

**Comment by marcusholl** [comment] 2019-03-28 12:55
I have no better idea.

We can see in the log:

```
java.io.FileNotFoundException: /home/jenkins/NEO_HOME/tools/log/session_deploy-mta_1553752313264.log (Permission denied)
```

From that log message I think we have these possible error causes:

- folder is missing
- the user running the process does not have permissions.

I am running out of other ideas ...

Which user is used for running Jenkins? Can be verified by having a look into Jenkins -> System Information, or maybe even better also be creating a free style job and executing a bash inside this with `whomai`

**Comment by pratibhakalmath** [comment] 2019-03-29 06:29
Hi Marcus, PFA of the system variables for the Jenkins. The credentials we are using to access the Jenkins to run the pipeline is not the same as the user or sudo-user mentioned in the screenshot , is this the cause of the issue ? Do the user or sudo-user mentioned in the screenshot have only access to run the pipeline?
![Jenkins(system properties)](https://user-images.githubusercontent.com/47742903/55213588-bd979a00-5219-11e9-99e0-a5aaea05a91d.png)

**Comment by marcusholl** [comment] 2019-03-29 07:27
> The credentials we are using to access the Jenkins to run the pipeline is not the same as the user or sudo-user mentioned in the screenshot , is this the cause of the issue ?

There is a user used for running Jenkins. Very often this user is named `jenkins`. On most cases it is required to logon to Jenkins in order to see, trigger etc jobs. But the user used for executing shell calls from e.g. pipelines `sh` statement is the user running Jenkins: `jenkins`.

What I can see above is that the `USER` variable is `root`. With `root` there is normally never a permission issue with writing files. I can also see that the `OLDPWD` is `/home/ec2-user`. So somehow another user than `root` is in the game ...

I'm confused: we have users `root` and `ec2-user` now. On the other hand we can see that the`logs` directory is owned by `jenkins`. That seems inconsistent. 

Earlier you provided some output of a ls command inside `/home/jenkins/NEO_HOME/tools/logs`
From that we can see that the user `jenkins` is the owner of the `logs` directory and also the owner of all the files contained there. The corresponding user group for that is `users`. From the octets we can see that the user has `rw` permissions for that folder. The group has only read permissions.

This means that user `jenkins` can write file in this folder - or `root`. Just as a side note: In general I consider it as bad idea to run the Jenkins with `root`.

In case a shell is triggered from a pipeline the commands are issued under the user running Jenking. In case any other user than `jenkins`  (... or `root`) is used now, we will end up in a situation we have here.

Also in case another user is used for accessing the machine for e.g. troubleshooting we will see issues like here.

How should we proceed? Are you experiencing the issue with the log file while saying `neo.sh version`? In this case I would for the only reason of troubleshooing recommand to do this as root. With this there will be no problem since root can write anyway. Afterwards to the same with user `jenkins`. This should work also. In case there are no credentials for jenkins: it might be possible to `su` to `jenkins` when you are root.

In case there a real reason for invoking the neo toolset with another user (e.g. `ec2-user`): adjust the file permissions accordingy. E.g. in case that other user is also member or group `users`, adjust your file permissions so that the group `users` can also write.

**Comment by radsoulbeard** [comment] 2019-05-21 08:28
No update since more than a month. Close the issue.

**Closed as completed by radsoulbeard** 2019-05-21 08:28 UTC

**Comment by CCFenner** [comment] 2019-05-21 09:06
@pratibhakalmath you published your CP account name here to the public.
